config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :topics, only: :show do
    collection do
      get :search
    end
    resources :favorite_topics, only: :create

    resources :bookmarked_articles, only: :create
  end

  resources :favorite_topics, only: [:index, :destroy] do
    collection do
      get :tweets
    end
  end

  resources :bookmarked_articles, only: [:index, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmarked_article.rb
class BookmarkedArticle < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/favorite_topic.rb
class FavoriteTopic < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :favorite_topics
  has_many :bookmarked_articles

  validates :title, presence: true
  validates :icon_url, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :bookmarked_articles, dependent: :destroy
  has_many :favorite_topics, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookmarked_articles_controller.rb
class BookmarkedArticlesController < ApplicationController
  def index
    @bookmarked_articles = BookmarkedArticle.all
    # @bookmarked_article = BookmarkedArticle.find(params[:id])

  end

  def show
    @bookmarked_article = BookmarkedArticle.find(params[:id])
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmarked_article = BookmarkedArticle.new(strong_params)
    @bookmarked_article.user = current_user
    @bookmarked_article.topic = @topic
    @bookmarked_article.save

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @bookmarked_article = BookmarkedArticle.find(params[:id])
    @bookmarked_article.destroy

    redirect_to bookmarked_articles_path
  end

  private

  def strong_params
    params.require(:bookmarked_article).permit(:username, :text, :tweet_id, :followers)
  end
end

app/controllers/favorite_topics_controller.rb
class FavoriteTopicsController < ApplicationController
  def index
    # @favorite_topics = FavoriteTopic.all
    @favorite_topics = current_user.favorite_topics
    @topics = Topic.all
    @favorite_topics = @favorite_topics.map do |favorite_topic|
      bookmark_size = current_user.bookmarked_articles.where(topic: favorite_topic.topic).size
      [favorite_topic, bookmark_size]
    end
    # @favorite_topic = current_user.favorite_topics.find(params[:favorite_topic])

    # @favorite_topics_tweets = {}
    # @favorite_topics.each do |favorite_topic|
    #   @favorite_topics_tweets[favorite_topic.topic.title] = HandleTweets.new(favorite_topic.topic, 5).format_tweets
    # end
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @favorite_topic = FavoriteTopic.new
    @favorite_topic.topic = @topic
    @favorite_topic.user = current_user

    if @favorite_topic.save
      flash[:alert] = "#{@topic.title} has been added to your Favorite Topics"
      redirect_to topic_path(@topic)
    else
      render 'topic/show'
    end
  end

  def destroy
    @favorite_topic = FavoriteTopic.find(params[:id])
    @favorite_topic.destroy

    redirect_to favorite_topics_path
  end

  def tweets
    @topic = Topic.find(params[:topic_id])
    topic = { title: params[:title], cashtag: params[:cashtag] }
    @topic_tweets = HandleTweets.new(topic, 5).format_tweets
    @coingecko_id = params[:coingecko_id]
    @bookmarks = current_user.bookmarked_articles.where(topic: @topic)
    @favorite_topic_to_delete = current_user.favorite_topics.where(topic: @topic).first
    # p @topic_tweets
    # p @coingecko_id

    respond_to do |format|
      format.json
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @topics = Topic.all
    @blockchain_topic = Topic.find_by(title: 'Blockchain')
    @tweets_data = HandleTweets.new(@blockchain_topic, 3).format_tweets
    redirect_to topic_path(params[:search][:topic]) if params[:search]
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  def show
    @topic = Topic.find(params[:id])

    # raise
    @tweets_data = HandleTweets.new(@topic, 5).format_tweets
    @is_favorite = !FavoriteTopic.where(topic: @topic, user: current_user).empty?
  end

  def search
    @topic = Topic.find(params[:search][:topic])
    # raise
    redirect_to @topic
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookmarked_articles/create.js.erb
var replaceTweet = (topic_id, tweet_id, outerHTML) => {
  const tweetCards = document.querySelectorAll('.card')
  tweetCards.forEach((tweetCard) => {
    const cardTweetId = tweetCard.dataset.tweetId
    if(cardTweetId === tweet_id) {
      tweetCard.outerHTML = outerHTML
    }
  })

  const bookmarkTag = document.getElementById(`bookmark-tag-${topic_id}`)
  const bookmarkCount = parseInt(bookmarkTag.innerText) + 1
  bookmarkTag.innerText = bookmarkCount
  bookmarkTag.parentElement.style.opacity = 1

  const accordionTitle = document.querySelector('.accordion-title')
  const plural = bookmarkCount > 1 ? 'bookmarks' : 'bookmark'
  accordionTitle.innerText = `${bookmarkCount} ${plural}`

}

var alertMessage = (outerHTML) => {
  document.insertAdjacentHTML('beforeend', outerHTML)
}


<% if @bookmarked_article.persisted? %>
  var tweet_id = "<%= @bookmarked_article.tweet_id %>"
  var topic_id = "<%= @bookmarked_article.topic.id %>"
  replaceTweet(topic_id, tweet_id, ' <%= j render partial: "shared/tweet_bookmark", locals: { tweet: @bookmarked_article } %>')
<% else %>
  alertMessage( <%= j render partial: "shared/flashes", locals: { notice: @bookmarked_article.errors } %>')
<% end %>

app/views/bookmarked_articles/index.html.erb
<div class="container">
  <h1 class="text-center">Bookmarks</h1>

  <div class="cards">
    <% @bookmarked_articles.each do |article| %>
      <%= render 'shared/tweet_bookmark', tweet: article %>
    <% end %>
  </div>
</div>

app/views/bookmarked_articles/show.html.erb
<h1>Hello there!</h1>

<div class="cards">
  <div class="card w-100">
    <div class="card-body">
      <h5 class="card-title">@<%= @bookmarked_article.username%> </h5>
      <h6><%= number_to_human(@bookmarked_article.followers, units: { thousand: 'K', million: 'M' }) %> Followers </h6>
      <p class="card-text"><%= @bookmarked_article.text %></p>
      <ul class="d-flex justify-content-around p-0">
        <li class="list-unstyled">
          <%= link_to "https://twitter.com/#{@bookmarked_article.username}/status/#{@bookmarked_article.tweet_id}", target: '_blank' do %>
            <i class="fab fa-twitter"></i>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/favorite_topics/index.html.erb
<div class="container">
  <h1 class="topic-card-heading margin-top-30">My Topics</h1>
  <p class="topic-card-subheading">Favorite Topics you <span class="blue-text">follow</span></p>
</div>


<div data-controller="off-canvas">
  <div class="button-container d-flex flex-column justify-content-center">
    <%#= link_to 'Back', root_path, class: "btn bg-white text-dark" %>
    <button class="btn search-topic-button" data-action="click->off-canvas#search">Search Topic</button>
  </div>
  <div class="container">
    <div class="cards">
      <% @favorite_topics.each do |favorite_topic| %>
        <%= render 'shared/topic_card', favorite_topic: favorite_topic.first, bookmarks_count: favorite_topic.last %>
      <% end %>
    </div>
    <%= render 'shared/search_canvas', topics: @topics %>
    <%= render 'shared/off_canvas' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cryptocanons</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
  </head>

  <body>
    <div class="d-flex flex-column min-vh-100">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <article class="flex-grow-1">
        <%= yield %>
      </article>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
<div class="margin-top-50 main">
  <%= image_tag 'main.svg' %>
  <div class="container">
    <h1 class="margin-top-50 main-h1">Find all of your crypto news in one place</h1>
    <p class="main-p"><span>CryptoCanons</span> curates the best content on the internet that helps you make sense of crypto related news. <br>You are closer than ever to making the best investment decision of your life.</p>
    <div class="margin-top-30">
      <%= render 'shared/select_topic_form' %>
    </div>
  </div>
</div>

<div class="container margin-top-120 secondary">
  <h1>Discover the latest crypto news right from your phone</h1>
  <p>The most up-to-date news directly from Twitter including the current price and charts</p>
  <%= image_tag 'phone-good.png', class: 'center-image margin-top-50', data: { aos: "zoom-in" } %>
</div>

<div class="container margin-top-120 body">
  <div class="info-box" data-aos="fade-right">
    <%= image_tag 'home-body-1.svg', class: 'center-image margin-top-40' %>
    <h2 class="margin-top-40">Discover latest topics from the best</h2>
    <p class="">Receive tweets from the most knowledgable people in crypto</p>
    <p class="tag white-text">Discover</p>
  </div>
</div>

<div class="container margin-top-50 body">
  <div class="info-box" data-aos="fade-right">
    <%= image_tag 'home-body-2.svg', class: 'center-image margin-top-40' %>
    <h2 class="margin-top-40">Major coins and tokens represented</h2>
    <p class="">Find the best information even for the most obscure coins.</p>
    <p class="tag">Learn</p>
  </div>
</div>

<div class="container margin-top-50 body">
  <div class="info-box" data-aos="fade-right">
    <%= image_tag 'home-body-3.svg', class: 'center-image margin-top-40' %>
    <h2 class=" margin-top-40">Save your favorite topics and view them anytime</h2>
    <p class="">View all of your saved topics on a single beautifull display</p>
    <p class="tag white-text">Save</p>
  </div>
</div>

<div class="margin-top-120 quick-stats text-center">
  <p class="text-left">Explore</p>
  <h2 class="margin-top-50" data-aos="fade-right">200+ coins</h2>
  <h2 class="margin-top-30" data-aos="fade-right">Prices and trends</h2>
  <h2 class="margin-top-30" data-aos="fade-right">Freshest tweets</h2>
</div>

<div class="container margin-top-120 cta">
  <h2 class="center-image text-center">Get started in a few minutes</h2>
  <p class="margin-top-50"><i class="fas fa-check"></i> 100% Satisfaction Guaranteed</p>
  <p class="margin-top-30"><i class="fas fa-check"></i> 24/7 Support</p>
  <p class="margin-top-30"><i class="fas fa-check"></i> 4+ Satisfied Customers</p>
  <%= link_to 'Sign Up Now', new_user_registration_path, class: 'btn search-button margin-top-50'  %>
</div>

<%= render 'shared/footer_home' %>

app/views/shared/_accordion_bookmarks.html.erb
<div class="accordion mt-4 mb-5" id="accordionExample">
  <div class="card">
    <div class="card-header white-bg py-0 px-3 " id="headingOne">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left d-flex justify-content-between align-items-center" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          <p class="accordion-title"><%= pluralize bookmarks.count, "Bookmark" %></p>
          <i class="fas fa-list icon-font"></i>
        </button>
      </h2>
    </div>

    <div id="collapseOne" class="collapse bg-light" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
        <div class="cards p-0">
          <% bookmarks.each do |article| %>
            <%= render 'shared/tweet_bookmark.html.erb', tweet: article %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_article-card.html.erb
<div class="card w-100">
  <img src="https://images.unsplash.com/photo-1561451213-d5c9f0951fdf?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1489&q=80" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <ul class="d-flex justify-content-around p-0">
      <li class="list-unstyled">
        <%= link_to root_path do %>
          <i class="fab fa-twitter"></i>
        <% end %>
      </li>
      <li class="list-unstyled">
        <%= link_to root_path do %>
          <i class="far fa-newspaper"></i>
        <% end %>
      </li>
      <li class="list-unstyled">
        <%= link_to root_path do %>
          <i class="far fa-bookmark"></i>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_article_card.html.erb
<div class="card w-100">
  <img src="https://images.unsplash.com/photo-1561451213-d5c9f0951fdf?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1489&q=80" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <ul class="d-flex justify-content-around p-0">
      <li class="list-unstyled">
        <%= link_to root_path do %>
          <i class="fab fa-twitter"></i>
        <% end %>
      </li>
      <li class="list-unstyled">
        <%= link_to root_path do %>
          <i class="far fa-newspaper"></i>
        <% end %>
      </li>
      <li class="list-unstyled">
        <%= link_to root_path do %>
          <i class="far fa-bookmark"></i>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_chart_card.html.erb
<div class="w-100 my-1 margin-top-50 box" data-controller="chart">
  <%= link_to "Delete", favorite_topic_path(favorite_topic), method: :delete, remote: true, data: { confirm: "Are you sure?" }, class: "delete-link" %>

  <div class="d-flex justify-content-between align-items-start mb-5 text-left">
    <div class="d-flex mt-2">
      <button class="btn btn-outline-primary btn-sm mr-1" data-chart-target='button' data-action="click->chart#display" data-timeframe="365" data-change="1Y" data-index="0">1Y</button>
      <button class="btn btn-outline-primary btn-sm mr-1" data-chart-target='button' data-action="click->chart#display" data-timeframe="182" data-change="6M" data-index="1">6M</button>
      <button class="btn btn-outline-primary btn-sm mr-1" data-chart-target='button' data-action="click->chart#display" data-timeframe="90" data-change="3M" data-index="2">3M</button>
      <button class="btn btn-outline-primary btn-sm mr-1" data-chart-target='button' data-action="click->chart#display" data-timeframe="30" data-change="1M" data-index="3">1M</button>
      <button class="btn btn-outline-primary btn-sm mr-1" data-chart-target='button' data-action="click->chart#display" data-timeframe="7" data-change="7D" data-index="4">7D</button>
      <button class="btn btn-outline-primary btn-sm" data-chart-target='button' data-action="click->chart#display" data-timeframe="1" data-change="1D" data-index="5">1D</button>
    </div>
    <div class="mt-2 chart-price topic-card-price text-left">
      <p class="mb-0 text-left" data-chart-target='price'></p>
      <small data-chart-target='delta' class="text-left" style="font-size: 14px; display:block;"></small>
    </div>
  </div>
  <div class="card-body chart p-0" id="<%= coingecko_id %>" data-coingecko-id="<%= coingecko_id %>" data-chart-target="graph", data-bookmarks="<%= bookmarks.to_json %>">
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer_home.html.erb
<footer class="footer-home">
                <div class="footer-widgets">
                    <div class="footer-home-container">
                        <div class="row">
                            <div class="col-md-12">
                                <!-- Text widget-->
                                <aside class="widget widget-text">
                                    <div class="widget-title">
                                        <h6>About Us</h6>
                                    </div>
                                    <div class="textwidget">
                                        <p>Your best source for everything crypto.</p>
                                        <p>
                                            Location: Block 19, Dubai Knowledge Park, Dubai<br>
                                            E-mail: support@cryptocanons.com<br>
                                            Phone: 1-800-MY-CRYPTOCANONS<br>
                                        </p>
                                        <ul class="social-icons">
                                            <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                            <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                                            <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                            <li><a href="#"><i class="fab fa-pinterest-p"></i></a></li>
                                        </ul>
                                    </div>
                                </aside>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="footer-bar">
                    <div class="footer-home-container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="copyright">
                                    <p>© 2021 CryptoCanons, All Rights Reserved. </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>

app/views/shared/_hello_world.html.erb
<h1>hello</h1>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <p class="m-0 navbar-logo">CryptoCanons</p>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "My topics", favorite_topics_path, class: "nav-link border border-primary rounded text-center text-white mx-1 my-1 bg-primary nav-filled" %>
        </li>
        <%# <li class="nav-item active">
          <%= link_to "Bookmarks", bookmarked_articles_path, class: "nav-link border border-primary rounded text-center text-primary mx-1 my-1 bg-white nav-filled" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link border border-secondary rounded text-center mx-1 my-1 bg-transparent text-secondary" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link border border-primary rounded text-center text-white mx-1 my-1 bg-primary nav-filled" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link border border-primary rounded text-center mx-1 my-1 bg-transparent text-primary" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search-form.html.erb
<%= simple_form_for @topic, url: root_path, method: :get do |f| %>
  <%= f.input :select , as: :select %>
<% end %>

app/views/shared/_search_canvas.html.erb
<div class="off-canvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel" data-off-canvas-target="search">
  <div class="offcanvas-header">
    <div class="d-flex justify-content-end">
      <i class="far fa-times-circle" data-action="click->off-canvas#hideSearch"></i>
    </div>
  </div>
  <div class="offcanvas-body">
    <div class="d-flex justify-content-center align-items-center" style="height: 90vh;">
      <div class="bg-white p-5 rounded">
        <h5 class="offcanvas-title text-primary">Search Topic</h5>
        <hr>
        <p class="search-p mb-5">Search amongst 200 top cryptocurrencies to find the latest curated tweets and prices</p>
        <%= render 'shared/select_topic_form' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_topic_card.html.erb
<div class="topic-cards w-100"
    data-action="click->off-canvas#display"
    data-title=<%= favorite_topic.topic.title %>
    data-cashtag=<%= favorite_topic.topic.cashtag %>
    data-coingecko-id=<%= favorite_topic.topic.coingecko_id %>
    data-topic-id=<%= favorite_topic.topic.id %> >

  <%= image_tag(favorite_topic.topic.icon_url, class: 'crypto-icon') %>
  <div style="width: 75%;">
    <div class="d-flex justify-content-between mb-3">
      <div class="d-flex topic-card-info">
        <h2 class="crypto-title mb-0"><%= favorite_topic.topic.title.capitalize %></h2>
        <% if favorite_topic.topic.cashtag %>
          <h2 class="cashtag mb-0"><%= favorite_topic.topic.cashtag %></h2>
        <% end %>
      </div>
      <% opacity = bookmarks_count.positive? ? 1 : 0 %>
      <div class="d-flex align-items-center justify-content-center text-yellow position-absolute"
          style="font-size:13px; top: -2px; right: 20vw; opacity:<%= opacity %>">
        <h2 class="position-absolute text-dark" id="bookmark-tag-<%= favorite_topic.topic.id %>"  style="font-size:16px;"><%= bookmarks_count %></h2>
        <i class="fas fa-bookmark" style="font-size: 38px;"></i>
      </div>
    </div>

    <% if favorite_topic.topic.coingecko_id %>

        <div class="topic-card-price d-flex flex-column align-items-start">
          <p class="price mr-2 topic-" data-coingecko-id="<%= favorite_topic.topic.coingecko_id %>"></p>
          <p class="" style="font-size: 18px;"></p>
        </div>

    <% end %>
  </div>
  <p class="crypto-press"><i class="fas fa-caret-right"></i></p>
</div>

app/views/shared/_tweet_card.html.erb
<div class="card w-100 my-1 shadow-sm">
  <% if image_url %>
    <%= image_tag(image_url, {class: "card-img-top"}) %>
  <% end %>
  <div class="card-body">
    <div class="d-flex">
      <h5 class="card-title pr-2">@<%= username %> </h5>
      <small class="text-secondary"><%= number_to_human(followers, units: { thousand: 'K', million: 'M' }) %> Followers </small>
    </div>
    <p class="card-text"><%= text %></p>
    <ul class="d-flex justify-content-around p-0">
      <li class="list-unstyled">
        <%= link_to tweet_url, target: '_blank' do %>
          <i class="fab fa-twitter"></i>
        <% end %>
      </li>
      <% if article_url %>
        <li class="list-unstyled">
          <%= link_to article_url, target: '_blank' do %>
            <i class="far fa-newspaper"></i>
          <% end %>
        </li>
      <% end %>
      <li class="list-unstyled">
        <%= link_to bookmarked_articles_path(tweet: {username: username, text: text, followers: followers, tweet_id: tweet_id}), method: :post do %>
          <i class="far fa-bookmark"></i>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_tweet_partial.html.erb
<div class="card w-100 shadow-sm margin-bottom-30" data-tweet-id="<%= tweet['id'] %>">
  <div class="card-body">
    <p class="fresh-tag">New Tweet</p>
    <div class="d-flex justify-content-between align-items-center mb-3 margin-top-30">
      <h5 class="card-title pr-2">@<%= tweet['user']['username'] %> </h5>
      <small class="followers"><%= number_to_human(tweet['user']['public_metrics']['followers_count'], units: { thousand: 'K', million: 'M' }) %> Followers </small>
    </div>
    <p class="card-text margin-top-40 tweet-card"><%= tweet['text'] %></p>
  </div>

  <div class="d-flex form">

    <%# <%= link_to  topic_bookmarked_articles_path(topic: topic, tweet: {
          username: tweet['user']['username'],
          text: tweet['text'],
          followers: tweet['user']['public_metrics']['followers_count'],
          tweet_id: tweet['id']
          }),
        method: :post,
        class: 'btn bookmark-button not-rounded' do
    %>

    <%= simple_form_for [topic, BookmarkedArticle.new], remote: true do |f| %>
      <%= f.input :username, as: :hidden, input_html: { value: tweet['user']['username']} %>
      <%= f.input :text, as: :hidden, input_html: { value: tweet['text']} %>
      <%= f.input :followers, as: :hidden, input_html: { value: tweet['user']['public_metrics']['followers_count']} %>
      <%= f.input :tweet_id, as: :hidden, input_html: { value: tweet['id']} %>

      <%= button_tag type: 'submit', class: 'bookmark-button d-flex justify-content-center align-items-center' do %>
        <i class="far fa-bookmark mr-1"></i>
        <p class="mb-0">Bookmark</p>
      <% end %>
    <% end %>

    <%= link_to tweet['tweet_url'], target: '_blank', class: 'tweet-button tweet-button-position' do %>
      <i class="fab fa-twitter"></i>
      <p>Go to tweet</p>
    <% end %>

  </div>
</div>